language: c
compiler: gcc
script:
  - cd TEST
before_install:
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
script:
  - ./run_script
  - telnet localhost 11211
  - stats
  - quit
