language: c
before_install:
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
  - chmod +x run_script
compiler: gcc
script:
  - ./run_script
  - telnet localhost 11211
  - get key1
  - quit
  - echo "hello!"
