language: c
compiler: gcc

before_install:
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
script:
  - cd TEST
  - memcached -d -u travis -m 128 -p 11211 127.0.0.1
  - chmod +x run_script
  - ./run_script
  - ./memclient -s < testing.txt
  - ./memclient -g < testing.txt
  - { echo 'stats'; echo 'quit'; echo ; sleep 1; } | telnet localhost 11211
