language: c
compiler: gcc

before_install:
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
  - sudo apt-get install expect
script:
  - echo "Hello!"
  - cd TEST
  - memcached -d -u travis -m 128 -p 11211 127.0.0.1
  - chmod +x test_script.expect run_script.sh memclient.expect
  - ./run_script.sh
  - ./memclient.expect s key1 value1 60
  - ./test_script.expect localhost 11211
  - ./memclient.expect g key1
  - ./test_script.expect localhost 11211
  - ./memclient.expect d key1
  - ./test_script.expect localhost 11211
