language: c
compiler: gcc

before_install:
  - CD TEST
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
script:
  - ./run_script
  - telnet localhost 11211
  - stats
  - quit
