language: c
compiler: gcc

before_install:
  - sudo apt-get install libmemcached-dev
  - sudo apt-get install memcached
  - sudo apt-get install libevent-dev
  - sudo apt-get install expect
script:
  - echo "Hello!"
  - cd TEST
  - memcached -d -u travis -m 128 -p 11211 127.0.0.1
  - chmod +x test_script.expect
  - chmod +x run_script.sh
  - ./run_script.sh
  - ./memclient -s < testing.txt
  - ./memclient -g < testing.txt
  - ./test_script.expect localhost 11211
  - ./memclient -d < testing.txt
  - ./test_script.expect localhost 11211
